// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa4GVWs4KOHaImyJ1Mz6RCHv01a6RHyLo',
    appId: '1:729739531700:web:77774a9d113fcd4bda8ee1',
    messagingSenderId: '729739531700',
    projectId: 'sampahflutter',
    authDomain: 'sampahflutter.firebaseapp.com',
    storageBucket: 'sampahflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwEoq656JCSG-40NZCFSPph5nW9YeqseQ',
    appId: '1:729739531700:android:b7599018d5add5ceda8ee1',
    messagingSenderId: '729739531700',
    projectId: 'sampahflutter',
    storageBucket: 'sampahflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPdjjcFvHD9fYJ9JU9drXQ7FOLZiIKKQ',
    appId: '1:729739531700:ios:4c2bf41617e94ebdda8ee1',
    messagingSenderId: '729739531700',
    projectId: 'sampahflutter',
    storageBucket: 'sampahflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARPdjjcFvHD9fYJ9JU9drXQ7FOLZiIKKQ',
    appId: '1:729739531700:ios:4c2bf41617e94ebdda8ee1',
    messagingSenderId: '729739531700',
    projectId: 'sampahflutter',
    storageBucket: 'sampahflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa4GVWs4KOHaImyJ1Mz6RCHv01a6RHyLo',
    appId: '1:729739531700:web:be7b02b33538b669da8ee1',
    messagingSenderId: '729739531700',
    projectId: 'sampahflutter',
    authDomain: 'sampahflutter.firebaseapp.com',
    storageBucket: 'sampahflutter.firebasestorage.app',
  );
}
